### ISSUE TITLE
Gateway Error: Security header is not valid

### ISSUE THREAD

**Issue by MachineTobe** [spree-contrib/spree_paypal_express#39]
Hello Guys,

I've installed the gem, configured everything (step by step like described in the readme-file) but when I want to pay via paypal (clicking on the paypal express button in the cart) i got the message 'Gateway Error: Security header is not valid'.
I used the credentials from my Selling-paypal Sandbox account (tried them hundreds of times). What's the problem in this case? Would be great if somebody could help me.

Thanks, Tobi

**Comment by matteofuzz** [comment]
I confirm this error on 1-0-stable.
Instead on 1.0.0.rc4 it's run well.
I'm investigating...

**Comment by ipd** [comment]
I'm having the same issue.

**Comment by matteofuzz** [comment]
The problems rise from a preferences issue on 1-0-stable with boolean value on MYSQL db. I solved it upgrading to master (1.1.0.beta) (and using my fork of spree_paypal_express for the coupon issue).
On the stable it can't save and get the test_mode = true value.

With this gem it works:
GIT
  remote: git://github.com/spree/spree.git
  revision: ee874128f14642847bbb4f9ae30bd9341eb4a814
  specs:
    spree (1.1.0.beta)
...
GIT
  remote: git://github.com/matteofuzz/spree_paypal_express.git
  revision: ad84dcc9fb3d7cac85686e53c8cf20994cdf6763
  specs:
    spree_paypal_express (1.1.0)
      spree_core (> 0.9)

**Comment by radar** [comment]
This happens because you've entered the login, password or signature incorrectly for your payment method. You've probably noticed this by now, but I thought I'd mention it anyway.

The preferences could've also had something to do with it (and that's more likely), but this problem should now be solved.

**Comment by noff** [comment]
Error still appears on Spree 2.3.2beta.
Set PayPal credentials, form order, checkout, click "Pay with PayPal" and get "PayPal failed. Security header is not valid".
Reproduced on clean Spree branch-2.3 installation (Rails 4.1.2, sqlite3)

**Comment by poguez** [comment]
@noff could you get it work?

**Comment by amitpatelx** [comment]
I am also getting the issue with 2.3-stable and Rails 4.1.15. It works fine on live but issue with sandbox on local environment
